/*
    Warning - this file was autogenerated by genparse
    DO NOT EDIT - any changes will be lost
*/

#ifndef COMMAND_PARSE_H
#define COMMAND_PARSE_H

#include <message_.h>

#ifdef __XAP__
#include <source.h>
#endif

const uint8 *parseData(const uint8 *s, const uint8 *e, Task task);
void handleUnrecognised(const uint8 *data, uint16 length, Task task);

#ifdef __XAP__
uint16 parseSource(Source rfcDataIncoming, Task task);
#endif

struct sequence
{
  const uint8 *data;
  uint16 length;
};

struct command_adc_get
{
  uint16 channel;
};
struct command_gpio_pin_get
{
  uint16 pin;
};
struct command_gpio_set
{
  uint16 bits;
  uint16 mask;
};
struct command_gpio_pin_set
{
  uint16 pin;
  struct sequence value;
};
struct command_gpiodir_pin_get
{
  uint16 pin;
};
struct command_gpiodir_set
{
  uint16 bits;
  uint16 mask;
};
struct command_gpiodir_pin_set
{
  uint16 pin;
  uint16 value;
};
struct command_gpiosbias_pin_get
{
  uint16 pin;
};
struct command_gpiosbias_set
{
  uint16 bits;
  uint16 mask;
};
struct command_gpiosbias_pin_set
{
  uint16 pin;
  uint16 value;
};
struct command_gpio_watch_set
{
  uint16 count;
  uint16 mask;
  uint16 period;
};
struct command_rts_set
{
  uint16 value;
};
struct command_poll_set
{
  struct sequence input;
  uint16 period;
};
struct command_pskey_get
{
  uint16 pskey;
};
struct command_sleep_set
{
  uint16 state;
};
void command_ok(Task );
void command_adc_get(Task , const struct command_adc_get *);
void command_clk_get(Task );
void command_cts_get(Task );
void command_gpio_get(Task );
void command_gpio_pin_get(Task , const struct command_gpio_pin_get *);
void command_gpio_set(Task , const struct command_gpio_set *);
void command_gpio_pin_set(Task , const struct command_gpio_pin_set *);
void command_gpiodir_get(Task );
void command_gpiodir_pin_get(Task , const struct command_gpiodir_pin_get *);
void command_gpiodir_set(Task , const struct command_gpiodir_set *);
void command_gpiodir_pin_set(Task , const struct command_gpiodir_pin_set *);
void command_gpiosbias_get(Task );
void command_gpiosbias_pin_get(Task , const struct command_gpiosbias_pin_get *);
void command_gpiosbias_set(Task , const struct command_gpiosbias_set *);
void command_gpiosbias_pin_set(Task , const struct command_gpiosbias_pin_set *);
void command_gpio_watch_set(Task , const struct command_gpio_watch_set *);
void command_rts_set(Task , const struct command_rts_set *);
void command_software_version(Task );
void command_poll_reset(Task );
void command_poll_set(Task , const struct command_poll_set *);
void command_pskey_get(Task , const struct command_pskey_get *);
void command_temp_get(Task );
void command_alloc_get(Task );
void command_bt_version_get(Task );
void command_sleep_set(Task , const struct command_sleep_set *);
void command_local_version_get(Task );

#endif
